### ISSUE TITLE
GitHub Topics

### ISSUE THREAD

**Issue by ax3l** [epfl-scitas/spack-repo-externals#1]
Hi @alalazo ,

just for reference and community - should we think about adding [GitHub tags/topics](https://help.github.com/articles/classifying-your-repository-with-topics/) to external spack repos on GitHub? I think that could be useful!

What about
- [`spack-packages`](https://github.com/topics/spack-packages)

or
- [`spack`](https://github.com/topics/spack)
- `spack-repo`
- `package-management`

?

I publish our "experimental"/"unstable"/"external" packages in https://github.com/ComputationalRadiationPhysics/spack-repo

**Comment by alalazo** [comment]
@ax3l In general I think it's a very good idea to collect common configurations or tag custom repositories, like [HEP](https://github.com/HEP-SF/hep-spack) or yours. 

Here the case is a bit different: this repo contains only stub packages, that are mostly used to generate module files for third party code, so I am not sure how much of use this would be to somebody else.

**Comment by alalazo** [comment]
That said, I think `spack-packages` and `spack-configuration` could be two useful GitHub topics.
